---
title: The QSkinny UI framework
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: A documentation theme
palette: blue
palettes:
  blue:
    sass:
      accent1: '#0093ff'
      accent2: '#0072ff'
  green:
    sass:
      accent1: '#12db5d'
      accent2: '#11998e'
  navy:
    sass:
      accent1: '#004e92'
      accent2: '#000428'
  violet:
    sass:
      accent1: '#8e2de2'
      accent2: '#4a00e0'
header:
  title: ''
  #logo_img: images/logo.svg
  has_nav: true
  nav_links:
    - label: Home
      url: /
      style: link
      has_subnav: false
    - label: Documentation
      url: /docs
      style: link
      has_subnav: false
    - label: GitHub
      url: 'https://github.com/uwerat/qskinny'
      style: primary
      has_subnav: false
footer:
  content: >-
    &copy; Stackbit. All rights reserved. This Jamstack site was created on <a
    href="https://www.stackbit.com" target="_blank" rel="noopener">Stackbit</a>.
    Get yours <a href="https://app.stackbit.com/create?theme=libris"
    target="_blank" rel="noopener">here</a>.
  has_social: true
  social_links:
    - label: Twitter
      url: 'https://twitter.com/'
      style: icon
      icon_class: fa-twitter
      new_window: true
    - label: LinkedIn
      url: 'https://www.linkedin.com/'
      style: icon
      icon_class: fa-linkedin
      new_window: true
    - label: GitHub
      url: 'https://github.com/'
      style: icon
      icon_class: fa-github
      new_window: true
sass:
  indentWidth: 4
  style: nested
  precision: 10
plugins:
  - jekyll-menus
  - jekyll-asciidoc
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
